-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : Dim 10 juil. 2022 à 19:09
-- Version du serveur :  5.7.24
-- Version de PHP : 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `laravel_api_rest_db`
--

-- --------------------------------------------------------

--
-- Structure de la table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2022_07_05_173315_create_products_table', 1);

-- --------------------------------------------------------

--
-- Structure de la table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `products`
--

CREATE TABLE `products` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Synopsis` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Score` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Image` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `products`
--

INSERT INTO `products` (`id`, `title`, `Synopsis`, `Score`, `Image`) VALUES
(1, 'Initial D First Stage', 'Takumi est un jeune collégien de 18 ans, travaillant dans une station essence avec son ami Itsuki. Cela fait 5 ans qu\'il effectue des livraisons au volant d\'une AE86 pour son père qui tient un magasin de Tofu. Lorsqu\'il a commença à effectuer les livraisons il n\'avait pas son permis. Il habite sur les collines du Mt. Akina et tous les jours très tôt le matin il effectue des livraisons de Tofu. Avec les années, il gagne en adresse, apprend à drifter dans les virages pour gagner du temps, ce qui fait qu\'il maîtrise sa voiture et l\'art du drift à la perfection. Il n\'apprécie pas particulièrement rouler, pour lui c\'est un travail et non un plaisir. Mais à la suite d\'une course que son père le poussa à effectuer, il naît en lui un désire pour le street race. Takumi commence alors à s\'intéresser de plus près à sa voiture et aux courses.\r\n', '8.31', 'https://cdn.myanimelist.net/images/userimages/4869.jpg?t=1511766600'),
(2, 'Gekkan Shoujo Nozaki-kun', 'Depuis qu\'elle a croisé la route d\'Umetarô Nozaki, Chiyo Sakura en est tombé amoureuse. Mais le jour où elle se décide enfin à lui déclarer sa flamme, le jeune homme interprète mal ses paroles et est persuadé qu\'elle est une de ses fans.\r\nChiyo va alors découvrir qu\'en plus d\'être lycéen, Nozaki est aussi un mangaka plutôt populaire et qu\'il avait l\'intention depuis longtemps de faire d\'elle son assistante car il avait remarqué ses talents de coloriste.', '7.85', 'https://cdn.myanimelist.net/images/userimages/3667805.jpg?t=1584264000'),
(3, 'Gyakkyou Burai Kaiji: Ultimate Survivor', 'Japon, 1995. Après avoir fini l\'enseignement secondaire, Itō Kaiji déménage à Tōkyō pour trouver un emploi stable mais n\'y parvient pas à cause de son caractère atypique et de la première récession que connait le Japon depuis la fin de la Seconde Guerre mondiale. Déprimé, il végète dans son appartement, avec un quotidien fait de petits délits, de tabac et d\'alcool. Kaiji ne cesse de penser à sa situation financière, ce qui le pousse aux larmes à de nombreuses reprises. \r\nKaiji vit dans cet état d\'esprit pendant deux ans, jusqu\'au jour où un inconnu nommé Endō vient lui réclamer une dette astronomique endossée par Kaiji. Celui-ci laisse le choix à Kaiji : soit il travaille dix ans afin de rembourser la dette, soit il embarque à bord du casino flottant Espoir (en français dans le texte) dans l\'espoir de toucher un pactole en l\'espace d\'une seule nuit…                                                                                                                                                           \r\n', '8.28', 'https://cdn.myanimelist.net/images/userimages/5406.jpg?t=1612044000'),
(4, 'Ashita no Joe', 'Joe Yabuki, 15 ans, est un jeune orphelin roublard et bagarreur. Arrivant dans un bidonville, ses talents au combat attirent l\'intérêt de Tange Danpei, ancien boxeur alcoolique qui décide de l\'entraîner pour en faire un boxeur exceptionnel. Seulement, Joe Yabuki n\'est pas trop intéressé par cette idée... et a des problèmes avec les autorités.\r\n', '8.28', 'https://cdn.myanimelist.net/images/userimages/728.jpg?t=1462443600'),
(5, 'Shiki', 'Sotoba est un petit village cerné par les montagnes. Par une journée caniculaire, trois cadavres y sont découverts, sans qu’on puisse déterminer avec certitude les causes de leur mort. Au même moment, Megumi Shimizu, une jeune lycéenne, disparaît après avoir fait la connaissance des Kirishiki, une famille qui vient juste de s’installer dans un château sur les hauteurs du village. D’étranges événements se succèdent alors, qui ne sont que les prémisses d’un été terrifiant !\r\n', '7.74', 'https://cdn.myanimelist.net/images/userimages/19870.jpg?t=1649045400'),
(6, 'Higurashi no Naku Koro ni', 'L\'histoire se déroule en 1983, dans un petit village du nom de Hinamizawa. Keiichi Maebara, un jeune garçon, vient de déménager, et il doit intégrer la seule école du coin, où tous les âges se croisent dans une seule et même classe… Rapidement, il va se faire de nouvelles amies : Rena, Satoko, Mion et Rika. Keiichi va également apprendre l\'effrayante histoire de Hinamizawa, une histoire d\'horribles meurtres liés plus ou moins au projet de barrage\r\n dans le village. Malheureusement pour lui, il semblerait que ses nouvelles amies cachent elles-mêmes un très lourd secret à ce sujet…\r\n', '7.90', 'https://cdn.myanimelist.net/images/userimages/101649.jpg?t=1258388400'),
(7, 'Yamada-kun to 7-nin no Majo (TV)', 'Ryû Yamada est un élève de 2ème année au lycée privé de Suzaku. Celui-ci est toujours en retard, s\'endort pendant les cours et ses notes sont désastreuses. Sa vie quotidienne est ennuyante. D\'un autre côté, Urara Shiraishi qui, en plus d\'être très belle, est la meilleure élève du lycée. Mais un jour, après une soudaine chute dans l\'escalier, leurs corps sont échangés ! Ainsi Ryû se retrouve avec le corps de Urara et Urara celui de Ryû !\r\n', '7.57', 'https://cdn.myanimelist.net/images/userimages/4538045.jpg?t=1653330000'),
(8, 'Ookami to Koushinryou', 'Lawrence est un marchand ambulant qui vend de la fourrure et fait des échanges. En raison de son travail, il retourne dans le village de Pasroe au moment du festival de la moisson. Contrairement au reste du pays, les habitants sont païens et croient en une divinité-loup : Horo. La légende raconte qu’un pacte entre les hommes et les loups a été conclu afin d’assurer le bon fauchage du blé quand celui-ci aurait atteint la maturité escomptée. Cependant, en raison des nouvelles méthodes inventées, les habitants du village n’ont plus aucune difficulté pour faucher le blé. Ils ont ainsi fini par ne plus prendre la légende au sérieux et ne plus réellement croire en l’existence de Horo. Alors qu’il s’apprête à quitter le village, Lawrence découvre à l’arrière de sa carriole une jeune femme possédant des oreilles et une queue de loup. Cette dernière se présente alors comme la divinité des lieux et, étant donné que les habitants ne semblent plus avoir besoin d’elle, demande à Lawrence de l’emmener avec lui. Un nouveau partenariat entre l’homme et le loup se forme alors, permettant à ces deux caractères si différents de se comprendre mutuellement.\r\n', '8.23', 'https://cdn.myanimelist.net/images/userimages/2220.jpg?t=1618297200'),
(9, 'Masamune-kun no Revenge', 'Lorsqu’il était enfant, Masamune Makabe était un garçon rondouillard dont se moquait souvent une fille, Aki Adagaki. Il a fini par décider de se prendre en main et, quelques années plus tard, le voilà devenu un beau jeune homme intelligent et athlétique. À présent, il est prêt à prendre sa revanche sur ceux qui l’ont humilié ! Et il compte bien profiter d’un changement d’école pour mettre ses projets en œuvre…\r\n', '6.75', 'https://cdn.myanimelist.net/images/userimages/4673091.jpg?t=1656981600'),
(10, 'Zero no Tsukaima', 'Louise Françoise Le Blanc de La Valière, étudiante de seconde année à l\'académie de magie Tristein est célèbre parmi ses camarades pour avoir un taux de réussite de zéro pour ses sorts. Qui plus est, à chaque fois qu\'elle brandit sa baguette, elle provoque une explosion.\r\nLe jour où les étudiants de seconde année accomplissent le rituel d\'invocation qui leur permettra de faire apparaitre leur \"familier\", et alors que ses camarades invoquent différentes créatures magiques, Louise convoque un jeune homme endormi. Alors qu\'elle scelle un pacte avec lui par un baiser, des mystérieuses rune apparaissent sur la main de ce dernier....\r\n', '7.25', 'https://cdn.myanimelist.net/images/userimages/51006.jpg?t=1457060400'),
(11, 'Boku wa Tomodachi ga Sukunai', 'Kodaka Hasegawa est un étudiant comme les autres. Malheureusement, le premier jour dans son nouveau lycée ne se passe pas comme prévu. À cause de son air de délinquant, les rumeurs sur lui circulent déjà, et il ne parvient donc pas à se faire des amis. C\'est alors qu\'il surprend Yozora Mikazuki en train de parler toute seule. Ayant pour point commun la solitude, ils décident de fonder un club… un club pour se faire des amis ! Ils se lancent donc à la recherche de nouveaux membres et dans des activités dont ils n\'avaient pas l\'habitude jusqu\'à présent…\r\n', '7.19', 'https://cdn.myanimelist.net/images/userimages/207137.jpg?t=1649854200'),
(12, 'Trinity Seven', 'L’histoire nous entraîne dans le quotidien de Kasuga Arata, un adolescent qui vit avec sa cousine, Hijiri.Sa vie bascule quand il apprend que son monde est en réalité anéanti et qu’il n’existe que dans un monde virtuel qu’il a lui même crée à l’aide d’un mystérieux Grimoire.Lilith, élève de l’Académie Magicus, a été envoyée pour retrouver le Grimoire. Menacé de mort par cette dernière, Kasuga n’a d’autre choix que de rejoindre l’Académie afin d’apprendre la magie et tenter de retrouver sa cousine\r\n', '7.08', 'https://cdn.myanimelist.net/images/userimages/3632359.jpg?t=1644843000'),
(13, 'Kokoro Connect', 'Ici, on suit le quotidien spécial de cinq jeunes garçons et filles au sein de leur club, dans le lycée Yamahoshi.\r\nIl s\'agit du club de culture générale, mais celui-ci se démarque des autres en raison des activités particulières qui s\'y déroulent. En effet, être capable d\'échanger mutuellement son corps avec celui d\'un autre est un phénomène pas très banal... Et ces cinq membres le prouvent. De cette étrange manière, ils vont peu à peu tisser des liens au delà de l\'amitié...\r\n', '7.77', 'https://cdn.myanimelist.net/images/userimages/2289799.jpg?t=1655679000'),
(14, '5-toubun no Hanayome', 'Fûtarô Uesugi est un lycéen issu d\'une famille modeste. Un jour, il reçoit une alléchante proposition pour un poste fort bien rémunéré en tant que professeur particulier à temps partiel. Mais voilà, les filles dont il doit s\'occuper sont dans sa propre classe ! De plus, ce sont des quintuplées ! Toutes les cinq sont très séduisantes, mais ce sont des élèves à problèmes car elles détestent étudier et leurs notes s\'en ressentent. La première mission de Fûtarô sera donc de gagner la confiance des sœurs Nakano...\r\n', '7.68', 'https://cdn.myanimelist.net/images/userimages/6017253.jpg?t=1656945600'),
(15, 'Kanojo, Okarishimasu', 'Largué par sa petite-amie, Kazuya Kinoshita tente de combler le vide dans son cœur à l\'aide d\'une application en vogue permettant de louer une nouvelle copine. C\'est ainsi qu\'il fait la rencontre de Chizuru Mizuhara, une jeune fille à première vue parfaite possédant tout ce que le jeune homme recherche : très belle et avec une personnalité mignonne et attentionnée. Il va cependant rapidement se rendre compte de la vraie personnalité de Mizuhara\r\n', '7.22', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(16, 'Bokutachi wa Benkyou ga Dekinai', 'Nariyuki Yuiga, étudiant en Terminale, s\'est consacré à devenir un élève de haut niveau dans son école, malgré ses mauvaises notes. Afin de donner à sa famille, dans le besoin financièrement, une vie meilleure, son but ultime est d\'obtenir la nomination spéciale VIP, une bourse prestigieuse couvrant tous les frais de scolarité universitaires futurs. Bien que Nariyuki puisse sans doute être un acteur important de la nomination, il est constamment éclipsé par ses camarades de classe Rizu Ogata et Fumino Furuhashi, respectivement en mathématiques et en littérature.\r\n\r\nPour son plus grand bonheur, Nariyuki reçoit la nomination, il y a cependant une condition : il doit encadrer ses deux camarades de classe, Rizu dont la littérature et les arts sont de terribles sujets pour elle et Fumino qui est épouvantable en mathématiques.\r\n\r\nPour couronner le tout, les sujets où elles sont mauvaises, sont en lien avec leur projet d\'avenir. La date limite pour soumettre ses candidatures universitaires se rapprochant, Nariyuki doit trouver une méthode de tutorat efficace avant qu\'il ne soit trop tard.', '7.30', 'https://cdn.myanimelist.net/images/questionmark_50.gif'),
(17, 'Dakara Boku wa, H ga Dekinai.', 'Ryôsuke Kaga est un lycéen dont la réputation n’est plus à faire : son obsession pour la gent féminine est connue de tous, caractéristique qu’il assume totalement. Un jour de pluie, en sortant du lycée, il croise une jolie jeune fille, trempée, qu’il recueille. Cette demoiselle, Lisara Restall, s’avère être une déesse de la Mort à la recherche d’un être spécial. Elle établit un contrat provisoire avec Ryôsuke, ce qui lui permet d’aspirer l’énergie du jeune homme dont elle a besoin pour mener sa mission à terme. Seulement, cette énergie est issue de l’esprit débauché du lycéen… -Sara-\r\n', '6.57', 'https://cdn.myanimelist.net/images/userimages/2935173.jpg?t=1654741800'),
(18, 'Asobi ni Iku yo!', 'Kio Kakazu, jeune lycéen, vit dans la chaleureuse région d\'Okinawa. Pourtant, sa vie jusqu\'alors ordinaire va être bouleversée lorsqu\'il fait la connaissance d\'une jeune demoiselle le jour de la commémoration de la mort de son grand-père.\r\nCette superbe extra-terrestre version Catgirl (fille ayant des oreilles et une queue de chat) dit s\'appeler Elis et être venue sur Terre dans le but de faire des recherches et de s\'amuser : de nature curieuse et enjouée, elle se familiarise rapidement avec Kio.\r\nMais la venue d\'Elis contrarie les projets de certains groupements secrets, et notamment de Manami-chan et de Futaba-san, membres d\'organisations rivales... Et attirées par notre héros !\r\n ', '6.60', 'https://cdn.myanimelist.net/images/userimages/218106.jpg?t=1525855800'),
(19, 'Hitsugi no Chaika: Avenging Battle', ' L’histoire nous entraîne dans le quotidien de Toru Acura, un soldat de 20 ans à la retraite depuis la fin de la guerre, qui vit avec sa sœur adoptive.                                                                                                                                                                                                                                                                                           \r\nUn jour, Toru fait la rencontre de Chaika, une mystérieuse fille qui porte un énorme cercueil sur son dos.\r\nDès lors, la vie du jeune homme prend un tout autre tournant…\r\n', '7.18', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(20, 'Arcana Famiglia', 'Regalo est une ile protégée par une organisation nommée Arcana Famiglia. À l’occasion du cinquante-neuvième anniversaire du chef de cette grande famille, celui-ci annonce qu’il va prendre sa retraite prochainement. Aussi organise-t-il sa succession : dans deux mois se tiendra un tournoi. Le vainqueur prendra la tête de l’organisation, il verra l’un de ses vœux exaucé et gagnera la main de Felicità. En attendant le début des combats, les membres de l\'Arcana Famiglia continuent d’accomplir leur mission — garantir la sécurité sur l’ile — tout en perfectionnant les pouvoirs dont ils sont dotés…\r\nL\'histoire se déroule dans la ville fictive de Kazamatsuri, où la végétation est omniprésente. En effet, suite à différentes politiques de boisement, la végétation a proliféré donnant à la ville une morphologie unique mêlant arbres et architecture traditionnelle.\r\n', '6.26', 'https://cdn.myanimelist.net/images/userimages/1904192.jpg?t=1602814200'),
(21, 'Asu no Yoichi!', 'Yoichi Karasuma, un garçon de 17 ans qui vit avec son père dans les montagnes il va dans l\'école Ukiha Kamikaze ou il apprend l\'art du Kendô. Mais un jour arrive ou son père l\'envoi en ville pour apprendre la vie en société et renforcer son esprit dans le but de devenir un digne samouraï.\r\n\r\nIl rejoins un autre dôjô faisant parti de l\'école Ukiha Kamikaze qui est dirigé par la famille Ikaruga. Ce dôjô est tenu par quatre sœurs : Ibuki (17 ans), Ayame (16 ans), Chihaya (15 ans) et Kagome (10 ans). Mais Yoichi découvre qu\'il a peur des filles, la moindre apparence, le moindre regard, le moindre mouvement ou si elle lui parle, il perd tout ses moyens, devient rouge et fini par faire n\'importe quoi. Il apprend un peu plus tard qu\'en faite son père l\'as envoyé pour lui jouer un tour...\r\n\r\nIl devra tout faire pour se sortir de ces situations plus que périlleuses.\r\n', '6.72', 'https://cdn.myanimelist.net/images/userimages/48866.jpg?t=1649241000'),
(22, 'Rewrite', 'Kotarô Tennôji, lycéen à Kazamatsuri, possède la faculté d\'adapter (rewrite) son propre corps. Il peut ainsi devenir plus fort ou plus agile selon sa volonté.\r\nMembre du club d\'occultisme de son lycée, il enquête sur les phénomènes paranormaux en compagnie des autres membres, majoritairement des filles.\r\n', '6.66', 'https://cdn.myanimelist.net/images/userimages/4673091.jpg?t=1656981600'),
(23, 'Aku no Hana', 'Kasuga Takao est un lycéen amoureux de sa camarade de classe, Saeki Nanako.\r\nUn jour, Takao vole le short de sport de la jeune fille. Le lendemain, une élève, Nakamura Sawa, lui révèle qu’elle a tout vu.\r\nMaintenant, s’il ne passe pas un contrat avec elle, Nakamura Sawa le dénoncera à toute la classe. Et malheureusement pour lui, Nakamura est une véritable manipulatrice…\r\n', '7.14', 'https://cdn.myanimelist.net/images/userimages/1872716.jpg?t=1656703200'),
(24, 'Ladies versus Butlers!', 'L’histoire tourne autour d\'une personne, Akiharu Hino, un jeune lyçéen, qui ressemble bien malgré lui à un jeune délinquant. Il s’inscrira dans une académie qui était à l’origine une école pour jeune fille, pour suivre un entrainement intensif. Les étudiants sont inscrits dans cette académie pour devenir des servantes (Maid) ou des domestiques (Butler\r\n', '6.57', 'https://cdn.myanimelist.net/images/userimages/197890.jpg?t=1570928400'),
(25, 'True Tears', 'Shinichiro est un étudiant qui tente d’écrire une pièce en s’inspirant de son entourage. Un ami de son père étant mort l’année dernière, sa famille a pris sous tutelle sa jeune fille Hiromi qui se trouve être dans la même classe que Shinichiro. Ce dernier est attiré par elle et tente de comprendre pourquoi en sa présence, celle-ci reste renfermée sur elle-même. Cette attention particulière qu’il lui porte entraîne une certaine jalousie de la part de sa mère qu’il ignore complètement.\r\n', '7.30', 'https://cdn.myanimelist.net/images/userimages/45603.jpg?t=1654285200'),
(26, 'Seiren', 'Comme Amagami SS, la série sera découpée en trois arcs de quatre épisodes qui se focaliseront sur chacune des héroïnes. Les trois héroïnes principales sont Hikari Tsuneki, Tōru Miyamae et Kyouko Touno.\r\n\r\nL\'histoire prend place en été, durant la deuxième année du lycée des personnages principaux. Kamita Shouichi, un jeune lycéen, a peur de grandir. Un jour, sa professeur principale le convoque pour parler de ses plans de carrières. En chemin, Shouichi va rencontrer différents femmes qui vont le mener vers un futur inconnu\r\n', '6.29', 'https://cdn.myanimelist.net/images/questionmark_50.gif'),
(27, 'Dance in the Vampire Bund', 'Mina Tepes, Princesse et descendante d\'une grande famille de vampire, veut révéler au monde l\'existence des vampires.\r\nPour cela elle va créer une ville \"Vampire Bund\" à l\'aide d\' Akira Kaburagi où ces derniers pourront y vivre mais les humains et les vampires sont contre cet idée et vont se révolter et ainsi tenter de la tuer.\r\n', '7.01', 'https://cdn.myanimelist.net/images/userimages/207137.jpg?t=1649854200'),
(28, 'Omamori Himari', 'Yuto, descendant d\'une famille qui chasse les démons depuis la nuit des temps, s\'est vu confier par sa grand-mère une amulette le protégeant de leurs représailles. Seulement, le jour de son seizième anniversaire, celle-ci perd tout effet protecteur, et il se retrouve donc confronté aux attaques des démons qui veulent assouvir leur soif de vengeance. Heureusement, Himari, un esprit chat, apparaît devant lui comme sa nouvelle gardienne. \r\n', '6.86', 'https://cdn.myanimelist.net/images/userimages/99263.jpg?t=1656954600'),
(29, 'Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni Shimashita', 'Red est le frère aîné d\'une jeune héroïne se battant contre le Seigneur Démon. Néanmoins, lui ne possède que la capacité de Guide ne lui permettant pas d\'avoir recours à la magie, aux arts martiaux et même aux capacités spéciales, le faisant passer pour quelqu\'un de totalement inutile. C\'est ainsi qu\'il fut exclu du groupe de sa sœur, le cœur brisé. Désormais, il n\'aspire qu\'à mener une vie discrète à la frontière, à Zoltan, et ouvrir un magasin d\'herboriste.\r\n', '6.95', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(30, 'Koi to Senkyo to Chocolate', 'Yuuki Ojima fait partie du Club de recherche alimentaire dans une école privée qui dénombre plus de 6 000 étudiants.\r\nUn jour, l’un des lycéens les plus populaires propose lors de sa campagne pour devenir Président du Conseil des étudiants, de fermer tous les clubs improductifs, ce qui met en péril celui de Yuuki.\r\nSeule solution qui s’offre à notre jeune protagoniste; Concourir pour le poste de Président des élèves.\r\nMais s’attirer les faveurs des électeurs (et électrices) n’est pas aussi simple que prévu…\r\n', '7.01', 'https://cdn.myanimelist.net/images/userimages/3710831.jpg?t=1503631200'),
(31, 'Working!!!', 'Takanashi Souta est un lycéen qui a une passion pour les petites choses mignonnes. Quand une fille, Taneshima Popla, l\'aborde dans la rue et lui demande si il cherche un travail à mi-temps, il la trouve mignonne car elle ressemble à une collégienne, peut-être même une écolière. Mais il se rend compte quelle a un an de plus que lui. Passant par dessus ce détail, il accepte le travail à mi-temps car elle est toute petite et craquante à souhait. Il commence donc à travailler dans un restaurant familial, mais on peut dire que le personnel est unique ici !\r\n', '7.98', 'https://cdn.myanimelist.net/images/userimages/4692605.jpg?t=1638672600'),
(32, 'Devils Line', 'Tsukasa Taira est une jeune étudiante qui s\'est fait secourir lors d\'une attaque de vampires, ces démons qui se fondent dans la population humaine.\r\n\r\nYûki Anzai, son sauveur, est un policier moitié humain, moitié vampire qui utilise ses pouvoirs surnaturels pour combattre les menaces liées aux vampires dans la ville de Tokyo. Ces menaces concernent principalement les vampires qui ont franchit l\'interdit, celui de boire du sang humain.\r\n\r\nVu que Anzai continue de protéger Tsukasa, ils vont rapidement être attirés l\'un vers l\'autre.\r\n\r\nAlors qu\'ils passent de plus en plus de temps ensemble, Anzai a de plus en plus envie de boire du sang humain...', '6.83', 'https://cdn.myanimelist.net/images/userimages/6647699.jpg?t=1656976800'),
(33, 'ef: A Tale of Memories.', 'Hiro Hirono est un jeune auteur de manga. La veille de Noël, il se fait piquer son vélo par une étrange fille qui cherche à récupérer son sac à main, dérobé par un voleur. Echouant dans sa tache, elle casse le vélo de Hiro et décide de rester à ses côtés pour rembourser sa dette.\r\n\r\nKyosuke Tsutsumi fait partie du club de vidéo de son lycée. Alors qu\'il filme les gens faire leurs achats de Noël, il est interpellé par une jeune fille qui passe en courant dans la rue. Il essaye de capturer son image mais trop tard, la photo restera floue et l\'identité de la fille inconnue...\r\n\r\nRenji Asou est un grand rêveur et lecteur. Son lieu de prédilection est une gare abandonnée où il aime lire seul. Un jour, il y rencontre une jeune fille très douce qui cache un lourd secret dans un étrange journal rose qu\'elle garde toujours avec elle...\r\n\r\nCes trois histoires décousues les unes par rapport aux autres ont en fait un lien : une Eglise dans laquelle deux mystérieuses personnes attendent en silence la réalisation d\'une promesse qu\'ils se sont faite dans le passé...\r\nEf –a tale of memories raconte l\'histoire de ces âmes solitaires dans leurs grands moments de joie mais aussi de peine et de souffrance.', '7.90', 'https://cdn.myanimelist.net/images/userimages/11081.jpg?t=1656976800'),
(34, 'Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen', 'L\'Empire est doté d\'un grand niveau de connaissances et Nebulis est craint comme étant le «Pays des Sorcières». Sur le champ de bataille opposant ces deux pays, un jeune homme et une jeune femme se sont rencontrés : Iska, le plus jeune épéiste de l\'histoire de l\'Empire et Aliceliese Lou Nebulis IX, la princesse de la famille impériale surnommée \"sorcière de glace\".\r\nÉtant tous les deux ennemis jurés, ils doivent s\'entretuer. Cependant, Iska est tombé sous le charme de la beauté et la noblesse de Aliceliese. De son côté, elle est attirée par la force et le mode de vie du jeune homme.\r\nEnsemble, ils vont essayer d\'instaurer la paix entre les deux royaumes.\r\n', '6.63', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(35, 'Love Hina', 'Keitarô Urashima, vingt ans, a déjà raté deux fois le concours d\'entrée pour l\'université de Todai. Malgré ce rêve qui semble impossible à réaliser, il n\'abandonne pas, à cause d\'une promesse faite il y à quinze ans. À court d\'argent, il se retrouve gérant du pensionnat pour filles Hinata appartenant à sa grand-mère afin de poursuivre ses études. Malheureusement, il a beaucoup de difficultés à s\'intégrer et doit faire ses preuves pour pouvoir rester.', '7.11', 'https://cdn.myanimelist.net/images/userimages/11081.jpg?t=1656976800'),
(36, 'Tada-kun wa Koi wo Shinai', 'Mitsuyoshi Tada photographie les cerisiers en fleurs lorsqu’une jeune fille étrangère du nom de Theresa Wagner lui demande de la prendre en photo. Après l’avoir rencontrée par hasard plusieurs fois dans la journée, Mitsuyoshi décide d’inviter la jeune fille au café de son grand-père pour s’abriter de la pluie...', '7.57', 'https://cdn.myanimelist.net/images/userimages/5694873.jpg?t=1656958800'),
(37, 'Kanon (2006)', 'Nayuki Minase accueille son cousin Yûichi Aizawa, qui revient en ville après une absence longue de sept ans. Yûichi a perdu bon nombre de souvenirs concernant cette ville, y compris ses connaissances d’antan. Par chance, il arrive à reprendre contact avec elles, et c’est ainsi qu’avec le temps et à force de les côtoyer, sa mémoire se reconstitue tel un puzzle et lui permet de comprendre ce qui s’est produit lors de sa dernière visite…', '7.97', 'https://cdn.myanimelist.net/images/userimages/11081.jpg?t=1656976800'),
(38, 'Masou Gakuen HxH', 'L’histoire suit le quotidien de Kizuna Hida, un lycéen ayant la capacité HHG (Heart Hybrid Gear), qui intègre une école de défense pour combattre les envahisseurs extraterrestres. Reiri Hida, sa sœur aînée, voit en Kizuna le moyen parfait pour les apprenties combattantes de regagner de l’énergie plus vite en entretenant une relation avec lui. Voilà que commence pour notre jeune héros une vie des plus embarrassantes.', '6.14', 'https://cdn.myanimelist.net/images/userimages/3316339.jpg?t=1656727800'),
(39, 'Steins;Gate', 'Dans un quartier d\'Otaku à Akihabara, un groupe d\'amis modifient leurs micro-ondes de manière à en faire un dispositif qui leur permet d\'envoyer des messages écrits vers le passé.\r\nUne organisation, CERN, a mené différentes recherches à propos des voyages temporels.\r\nÀ présent, le groupe, ayant effectué plusieurs expériences diverses, doit absolument éviter de se faire capturer par cette organisation qui les perturbe en les traquant...', '9.08', 'https://cdn.myanimelist.net/images/anime/5/73199.jpg'),
(40, 'Yuragi-sou no Yuuna-san', 'Possédé par un esprit maléfique et portant sur le dos une dette énorme, il cherche à louer une chambre pas trop chère. Il arrive alors à la pension Yuragi, hôtel de sources chaudes au passé mystérieux. Résident à la pension des filles un peu déjantées, à commencer par Yûna, un esprit qui hante les lieux faute de pouvoir passer dans l’au-delà. Kogarashi s’installe finalement dans cet établissement hors norme exclusivement occupé par des jeunes filles, malgré les réticences de ces dernières…', '7.02', 'https://cdn.myanimelist.net/images/userimages/4454850.jpg?t=1656975000'),
(41, 'Koi wa Ameagari no You ni', 'On suit le quotidien de la jeune Akira Tachibana et celui de son entourage. Cette dernière a des sentiments pour son manager de 45 ans mais il est persuadé qu\'elle est systématiquement en colère contre lui. Il y a aussi son camarade de classe, Yoshizawa, qui ne la lâche pas d\'une semelle dès qu\'il en a l\'occasion mais se fait toujours lamentablement ignorer. Sa kohai, qu\'Akira encourage dès qu\'elle peut et qui est presque aussi bonne qu\'elle ne l\'était en course. Et puis il y a aussi ses amies au lycée ou encore ses collègues de travail !', '7.50', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(42, 'Bokutachi no Remake', 'Le rêve de Kyôya Hashiba, un développeur de jeux vidéo âgé de 28 ans, se retrouve brisé après la faillite de son entreprise. Il décide donc de retourner chez ses parents pour se reposer.\r\n\r\nSur place, il découvre la réussite des autres personnes de son âge et décide d\'aller sur son lit en regrettant les décisions qu\'il a pu faire. Cependant, lorsque ce dernier se réveille, il remarque avoir voyagé dix ans dans le passé.\r\n\r\nAinsi, il se retrouve à devoir étudier dans l\'école d\'art qu\'il était supposé avoir abandonné. Accompagné des créateurs qu\'il admirait auparavant, Hashiba va-t-il saisir cette deuxième chance pour changer les choses ?', '7.44', 'https://cdn.myanimelist.net/images/userimages/6448140.jpg?t=1656938400'),
(43, 'Just Because!', 'Nous suivons le quotidien de lycéens en fin d’année de Terminale qui attendent leur diplôme. Ils devront choisir ce qu’ils feront par la suite.\r\nEntre temps, un ancien camarade de collège qui avait déménagé subitement est transféré dans leur classe. Sa présence va faire remonter certains sentiments…', '7.25', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(44, 'Grancrest Senki', 'L\'histoire se passe sur un continent gouverné par le chaos. Les seules personnes capables de contrer cette menace et d\'apaiser le peuple sont les Lords, des seigneurs possédant le Crest, un sceau sacré.\r\n\r\nCependant, avant que tout le monde ne s\'en rende compte, les Lords ont commencé petit à petit à rejeter leur devoir pour se disputer des parties de territoires.\r\n\r\nCette série se centre sur Shiruka, une mage isolée qui déteste les Lords et d\'un chevalier errant nommé Theo, qui recherche de la puissance pour libérer son village natale des griffes des Lords.\r\n\r\nShiruka et Theo font le serment de reformer ce continent dominé par les guerres et le chaos.', '7.22', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(45, 'Air', 'Kunisaki Yukito est un jeune homme qui gagne sa vie grâce à des spectacles avec sa marionnette qu\'il contrôle sans fils. Il parcourt le monde à la recherche d\'une fille ayant des ailes lui permettant de voler, poursuivant ainsi le rêve de sa mère. Un jour il arrive dans un village et fait la rencontre de Misuzu, une jeune fille bizarre et naïve. La mère de celle-ci, une \"adulte\" irresponsable, accepte qu\'il loge chez elles s\'il s\'occupe de Misuzu et plus particulièrement de son reflexe : elle dit tout le temps \"Gao\" et cela l\'énerve. Il rencontre aussi Kano Kirishima, une fille mystérieuse qui dit pouvoir utiliser la magie et dont le meilleur ami est un adorable chien apellé Potato, ainsi que sa grande soeur qui tient la seule clinique du village. Il y a aussi Minagi, la premiere de la classe et son amie Michiru, une enfant pour le moins turbulante. Il va décider de rester quelque temps dans ce village où le rêve de beaucoup semble être de voler dans le ciel...', '7.28', 'https://cdn.myanimelist.net/images/userimages/33147.jpg?t=1442796600'),
(46, 'Taimadou Gakuen 35 Shiken Shoutai', 'Par le passé, les épéistes ont disparu au profit des magiciens. Cette fois, ce sont les magiciens qui vont disparaître pour laisser place à des personnes maniant des armes à feu. L’​AntiMagic Academy est un lieu qui a pour but de former des Inquisiteurs d’Hérétiques. Ils sont chargés de réprimer les menaces causées par des magiciens.\r\n\r\nC’est dans cette école que Takeru Kusanagi décide de s’inscrire. Cependant, il ne peut se battre qu’avec des épées. À cause de cela, il est relégué dans le 35ème peloton qui a la particularité de réunir les élèves les moins compétents de l’​académie. Il est un jour mystérieusement rejoint dans ce peloton par Ōka Ōtori, qui possède d’ores et déjà les qualifications requises pour chasser des sorciers.', '6.83', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(47, 'Jaku-Chara Tomozaki-kun', '\"La vie est un mauvais jeu vidéo, peu importe à quel point vous essayez, vous ne pouvez pas surmonter les caractéristiques qui vous sont données à la naissance.\"\r\n\r\nPour Tomozaki Fumiya, qui se considère comme étant au plus bas de la société, on ne peut rivaliser avec les personnes tout en haut, celles qui réussissent tout ce qu\'elles entreprennent. Sa seule fierté réside dans le nom Nanashi, celui qu\'il utilise pour le jeu vidéo nommé Atafami où il détient le titre du numéro un japonais.\r\n\r\nCependant, lorsqu\'il rencontre la deuxième meilleure joueuse japonaise, sa position est contestée. La vie est-elle réellement le meilleur des jeux ?', '7.14', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(48, 'Rikei ga Koi ni Ochita no de Shoumei shitemita.', 'Shinya Yukimura et Ayane Himuro sont deux scientifiques qui ont le même but : décrypter l\'amour, le quantifier et l\'analyser par le biais de la science. Ayant des sentiments réciproques l\'un pour l\'autre, ils vont faire équipe afin de prouver que l\'amour existe de façon bien concrète.', '7.37', 'https://cdn.myanimelist.net/images/userimages/8196116.jpg?t=1656961800'),
(49, 'Genjitsu Shugi Yuusha no Oukoku Saikenki', 'L\'histoire se centre sur Souma Kazuya, un jeune homme qui se retrouve transporté dans un autre monde. En arrivant, il découvre un pays au bord de la disparition entre la famine, la pauvreté et les risques d\'invasion.\r\n\r\nC\'est ainsi que Kazuya propose un plan au Roi qui a pour but de renforcer le pays économiquement et militairement parlant. Cependant, après en avoir discuté pendant deux jours entiers avec le Roi, ce dernier lui cède subitement son trône et lui offre la main de sa fille.\r\n\r\nAfin de l\'épauler dans son plan, Kazuya lance un appel à toute personne possédant un talent qui puisse être utile au pays. Pour départager les nombreux candidats, il organise des tournois dans les différentes catégories. A l\'issue de ces tournois, cinq personnes se retrouvent devant le Roi.\r\n\r\nKazuya réussira-t-il à sauver le pays avant que celui-ci ne sombre encore plus dans le chaos ?', '7.23', 'https://cdn.myanimelist.net/images/userimages/9953848.jpg?t=1656960000'),
(50, '3D Kanojo: Real Girl', 'Hikari Tsutsui est un otaku tout ce qu\'il y a de plus basique. Il déteste avoir affaire avec les autres et tout particulièrement avec sa classe. À cause de cela, il est moqué par ses camarades. Un jour, il doit nettoyer la piscine en compagnie d\'Iroha Igarashi, une jolie fille. Elle est d\'ailleurs tout ce qu\'il déteste chez les vraies filles ; elle sèche les cours, n\'a aucune amies du sexe féminin et bien plus encore. Pourtant, elle est gentille avec lui et l\'aidera même quand il sera de nouveau embêté par des élèves. Iroha pourrait bien changer la vie monotone d\'Hikari...', '6.84', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(51, 'Yojouhan Shinwa Taikei', 'L\'animé suis l\'histoire d\'un jeune étudiant, Watashi (\"moi\" en français), c\'est à dire un personnage dont le nom est inconnu.\r\n\r\nA la fin de sa première année de faculté, il se retrouvera projeté dans le passé, pour revenir au début de sa première année. A la fin de celle-ci, il retournera encore dans le passé, encore et encore...\r\nChaque nouvelles années, il choisira un nouveau club, et fera ainsi de nouvelles rencontres. Le phénomène se répètera et nous suivrons ses différents choix dans ce cycle sans fin.', '8.57', 'https://cdn.myanimelist.net/images/userimages/214227.jpg?t=1651695600'),
(52, 'Ore no Imouto ga Konnani Kawaii Wake ga Nai.', 'Kyosuke Kosaka, qui ne partage rien avec sa soeur Kirino, plus jeune et plus populaire que lui, va voir sa relation avec cette dernière changer du tout au tout lorsqu\'il découvrira qu\'elle a une passion un peu étrange, surtout pour une jeune fille : les jeux érotiques pour otakus, et plus particulièrement ceux sur le thème des petites soeurs.\r\nAlors qu\'il aura parfois du mal à la comprendre, son frère va néanmoins l\'aider à vivre au mieux sa passion dévorante, transformant ainsi leur relation en une réelle relation frère/soeur.', '6.95', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(53, 'Hentai Ouji to Warawanai Neko.', 'L’histoire se concentre sur Yoto Yokodera, un lycéen particulièrement pervers. Il maîtrise toutes les subtilités pour voir secrètement les filles dans des situations « embarrassantes ».\r\n\r\nMalheureusement, Yoto a une personnalité trop fragile : il se plaint sans cesse et c’est un vrai lâche.\r\n\r\nUn jour, son ami lui révèle l’existence d’une statue de chat capable de réaliser les voeux. L’occasion parfaite pour changer de personnalité ?', '7.18', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(54, 'Ookami Shoujo to Kuro Ouji', 'Erika Shinohara, vaniteuse élève de seconde, fait croire à tout le monde qu’elle vit une histoire d’amour sulfureuse et passionnée. Pourtant, à l’âge de 16 ans, Erika n’a même jamais eu de copain. Sommée d’apporter une preuve de son idylle, elle prend en photo un beau jeune homme croisé dans la rue qu’elle présente comme son petit ami. Malheureusement, celui-ci s’avère être un élève de son lycée dont la sournoiserie n’a d’égale que sa grande beauté. Erika se retrouve alors piégée par Sata, ce dangereux manipulateur qui ne taira son mensonge que si elle devient son esclave…', '7.07', 'https://cdn.myanimelist.net/images/userimages/5063637.jpg?t=1526040000'),
(55, 'Sora no Otoshimono', 'L\'histoire nous montre un garçon dans la ville de Sorami au Japon appelé Tomoki Sakurai qui est un jour invité par son amie d\'enfance Sohara Mitsuki ainsi qu\'Eishirō Sugata (le leader du club « Le Nouveau Monde ») à se retrouver à minuit pour observer un étrange objet aperçu dans le ciel de la ville. Finalement, Tomoki y va seul lorsqu\'il reçoit un appel alarmant de Sugata lui disant de fuir tout de suite car l\'objet est très près de lui. C\'est alors que quelque chose tombe droit sur Tomoki, l\'objet étrange se trouve être en réalité une créature appelée Angeloïde qui se nomme Ikaros.', '7.28', 'https://cdn.myanimelist.net/images/userimages/327663.jpg?t=1410515400'),
(56, 'Maoyuu Maou Yuusha', 'Dans un monde où les démons et les humains sont en guerre, Yuusha, un héros humain, arrive après un long voyage au château du Roi démon dans le but de le mettre à mort. Yuusha se rend alors compte que le Roi démon est en faite une Reine du nom de Maou. Elle lui explique que la guerre donne une raison aux êtres humains de travailler main dans la main et d’améliorer leur société dans son ensemble. Maou le convainc que les humains tomberont dans une guerre civile sanglante sans ce conflit avec les démons. Le Héros décide donc d’unir ses forces avec elle pour éviter cette catastrophe.', '7.25', 'https://cdn.myanimelist.net/images/userimages/1158933.jpg?t=1587032400'),
(57, 'Tokyo Ravens', 'Tsuchimikado Harutora fait parti de la prestigieuse famille Onmyouji, des exorcistes capables d’utiliser la magie et d’invoquer des shikigami (=Esprits).\r\nLe seul inconvénient, c’est qu’il ne peut voir (ressentir?) l’énergie spirituelle contrairement à sa cousine, Natsume, héritière de la famille Tsuchimikado.\r\nMais le quotidien de Harutora et ses 2 meilleurs amis, Hokuto et Toji, bascule lorsque Natsume réapparaît dans leur vie.', '7.45', 'https://cdn.myanimelist.net/images/userimages/2545867.jpg?t=1656635400'),
(58, 'Chobits', 'Hideki Motosuwa est un jeune étudiant qui vient de la campagne et qui monte à Tokyo pour préparer son examen d\'entrée à l\'université pour laquelle il a été recalé. Un soir, il trouve dans une poubelle un Persocon, une sorte d\'ordinateur personnel qui a une allure parfaitement humaine. En l\'occurrence, il s\'agit d\'un persocon avec le physique d\'une très jolie jeune fille, sans aucun programme d\'installé, donc complètement vierge.\r\nHideki va donc apprendre à Chii (c\'est le nom du persocon : le premier mot qu\'elle parvient à prononcer naturellement suite à son activation) progressivement à se comporter comme un humain... Jusqu\'où cette relation va-t-elle aller ?', '7.41', 'https://cdn.myanimelist.net/images/userimages/41218.jpg?t=1328515800'),
(59, 'Mayo Chiki!', 'Konoe Subaru, un très beau garçon de 17 ans, se présente comme étant le majordome de Suzutsuki Kanade au lycée. Tout se déroule au mieux, jusqu\'à ce qu\'un camarade de classe de Kanade, Sakamoto Kinjirou, découvre par accident le secret compromettant de Subaru...\r\nIl apprend que celui-ci est en réalité une fille ! Il parait que si sa véritable identité est révélée, elle n\'exercerait plus le travail de majordome. Avec ce qui vient de se produire, qu\'arrivera-t-il à Subaru et aux autres ?', '7.25', 'https://cdn.myanimelist.net/images/userimages/528137.jpg?t=1506732600'),
(60, 'Hajimete no Gal', 'Jun’ichi « Jun » Hashiba est un lycéen pas très assidu dont la seule préoccupation est de vouloir perdre sa virginité. Poussé par ses amis, il se met à genoux devant Yukana Yame et lui fait une déclaration d’amour. Et ça marche !\r\nÀ présent, Jun sort avec Yukana, mais il n’avait pas vraiment réalisé qu’elle était une fille ultra-branchée par la mode…', '6.29', 'https://cdn.myanimelist.net/images/userimages/3895399.jpg?t=1598540400'),
(61, 'Netoge no Yome wa Onnanoko ja Nai to Omotta?', 'Hideki Nishimura a avoué ses sentiments à une fille sur jeu en ligne, cependant cette fille s\'est révélée être une homme dans la vie réelle. Ce dernier décide de garder cette sombre partie de sa vie pour le passé et de ne plus jamais faire confiance aux \"femmes\" sur les jeux en ligne.\r\n\r\nCependant, un jour une fille en ligne lui avoue être amoureuse de lui et cette fois-ci il s\'agit bien d\'une lycéenne nommée Ako Tamaki.\r\n\r\nAko ne peut pas faire la différence entre le monde en ligne et la réalité et possède de grosses difficultés à communiquer avec les autre dans la vie réelle. Hideki et ses amis de la guilde décident de la guérir dans le monde réel et de la faire réagir.', '6.73', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(62, 'Tsuki ga Kirei', 'Les années collège dans la ville de Kawagoe ! Kôtarô travaille dans une librairie et il aimerait devenir écrivain. Akane est une jeune fille pleine d’énergie qui adore courir. Ils se retrouvent tous les deux dans la même classe et doivent s’occuper des équipements d’un festival de sport. Une relation naît doucement, malgré leurs caractères opposés, notamment à travers les nombreux échanges qu’ils ont sur LINE, un logiciel de discussion.\r\nMais il faut aussi compter sur Takumi, amoureux d’Akane depuis qu’il est au collège, ou encore Chinatsu, qui a des vues sur Kôtarô. Le printemps réserve bien des surprises…', '8.09', 'https://cdn.myanimelist.net/images/userimages/4604609.jpg?t=1656963600'),
(63, 'Ore no Kanojo to Osananajimi ga Shuraba Sugiru', 'Eita est un jeune lycéen ambitieux qui a pour objectif d\'intégrer la prestigieuse école de médecine de l\'université nationale. Pris par le divorce de ses parents et son projet d\'étude, il exclut la possibilité d\'avoir une petite amie. Cependant, un jour, la beauté de l\'école aux cheveux d\'argent, Masuzu Natsukawa, lui déclare sa flamme. Chiwa, son amie d\'enfance depuis l\'école primaire, voit cette déclaration d\'un très mauvais œil et décide de lutter contre Masuzu.', '6.96', 'https://cdn.myanimelist.net/images/userimages/4124845.jpg?t=1628599200'),
(64, 'Gosick', 'L\'histoire se déroule en 1924 dans un monde parallèle.\r\n\r\nKujo, un jeune garçon japonais, entre dans une grande école d\'aristocrates, dans le royaume francophone fictif de Saubure qui s\'étend à travers les Alpes de la Suisse à la Méditerranée et entre la France et l\'Italie.\r\n\r\nCependant, du fait de son statut d\'étranger, il reste dans son coin, et ne fréquente personne.\r\n\r\nJusque là, rien d\'anormal ne se produit... Mais lorsqu\'il rencontre la mystérieuse jeune Victorica, qui avec son esprit analytique résout des mystères sanglants, sa vie va changer, mais sûrement pas en bien ...', '8.06', 'https://cdn.myanimelist.net/images/userimages/19870.jpg?t=1649045400'),
(65, 'Hige wo Soru. Soshite Joshikousei wo Hirou.', 'Yoshida est un employé qui a le béguin depuis 5 ans pour sa collègue de travail, Airi. Après avoir pris son courage à deux mains pour lui déclarer sa flamme, le pauvre Yoshida se prend un râteau et se trouve à noyer son chagrin dans l\'alcool. Sur le chemin de sa maison, il tombe sur une lycéenne qui lui demande le gîte et le couvert en échange de faveurs sexuelles. Bien qu\'il ait rejeté ses avances, il l\'invite néanmoins chez lui. Le lendemain matin, elle se présente comme Sayu Ogiwara et lui révèle qu\'elle est en fuite depuis ces six derniers mois. Jusqu\'à maintenant, elle a offert son corps contre hébergement mais sa méthode s\'avère cette fois-ci inefficace sur Yoshida, qui reste de marbre face à ses tentatives de séduction. Au lieu de cela, il lui propose de s\'occuper des tâches ménagères. C\'est ainsi que commence une vie de cohabitation fort mouvementée entre un homme de 26 ans et une lycéenne fugueuse !', '7.30', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(66, 'Absolute Duo', 'Après avoir perdu un être cher, Tooru Konoe s’inscrit à l’Académie Kouryou afin de recevoir un Blaze, une puissante arme qui est la manifestation de son âme, pour se venger.\r\nMais pour Toru, son Blaze n’est pas une arme mais un bouclier.\r\nEt dans cette école qui enseigne les compétences de combat, et grâce au système de partenaire « Duo », il finit par vivre avec Julie Sigtuna, une jeune fille aux cheveux d’argent.', '6.45', 'https://cdn.myanimelist.net/images/userimages/3955909.jpg?t=1636729800'),
(67, 'Sankarea', 'Fils d’un prêtre, Chihiro Furuya est obsédé par les zombies. Il collectionne tous ce qui s\'y rapportent : films, jeux vidéo, mangas et objets en tous genres. Il rêve un jour de voir une jeune fille ramenée à la vie lui déclarer sa flamme, même si il sait que son rêve ne se réalisera jamais.\r\n\r\nSuite à la mort de son chat Babu, Furuya ne peut accepter cette fatalité et tente de le ramener à la vie grâce à un vieux livre décrivant le processus de création d’une potion de résurrection. Alors qu’il s’entraine dans un vieil entrepôt désaffecté, il fait la connaissance de Rea Sanka, la fille du directeur de l’école pour filles voisine. Elle avoue s’être enfuie de chez elle, ne supportant plus sa famille et sa vie actuelle. Elle éprouve même le désir de mourir afin de se réincarner.\r\n\r\nSuite à cet aveu, les deux adolescents vont tenter de trouver le moyen de réaliser leurs souhaits respectifs.', '7.30', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(68, 'Grisaia no Kajitsu', 'L’histoire se déroule à l’académie Mihama, un environnement fermé, dédié à l’apprentissage, loin des influences extérieures.Nous suivons le quotidien du seul garçon, Kazami Yuuji, fraîchement transféré, et de 5 jeunes filles qui ont leur propre raison d’étudier dans cet endroit.Et si les filles ont toutes un secret qu’elles ne veulent absolument pas dévoiler, le nouvel étudiant ne fait pas exception. Ce dernier découvrira bientôt que la vie ordinaire qu’il espérait à l’Académie Mihama ne sera pas de tout repos…', '7.50', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(69, 'Vampire Knight', 'Si les vampires sont bel et bien des êtres se nourrissant du sang humain, entraînant dans la plupart des cas la mort de ces derniers, certains savent contenir leur soif à l’aide de tablettes spéciales et vont jusqu\'à protéger les humains de leurs congénères.', '6.91', 'https://cdn.myanimelist.net/images/userimages/21756.jpg?t=1507852800'),
(70, 'Bakuman.', 'Moritaka Mashiro est un étudiant de neuvième année qui a un talent inné pour le dessin et Akito Takagi, le meilleur élève de sa classe veut devenir mangaka.\r\nAprès beaucoup d\'argumentation, Takagi convainc Mashiro de s\'associer pour créer ensemble le meilleur manga que le Japon n\'ait jamais eu.\r\nTakagi avec son don pour l\'écriture espère devenir un très grand mangaka et Mashiro avec son talent pour le dessin espère se marier avec la fille de ses rêves, Azuki Miho.', '8.20', 'https://cdn.myanimelist.net/images/userimages/321412.jpg?t=1421065800'),
(71, 'Kami nomi zo Shiru Sekai', 'Keima Katsuragi est un lycéen de dix-sept ans, connu sous le pseudonyme de Dieu Tombeur dans le monde obscur des jeux vidéo de drague. Du matin au soir, il reste les yeux rivés sur sa console portable enchaînant ses conquêtes virtuelles et dispensant des conseils avisés par Internet aux adeptes du genre. C\'est en croyant répondre au message de l\'un de ces derniers qu\'il signe par mégarde un contrat avec les enfers et se voit affublé d\'une apprentie démone nommée Elsea de Lute Irma (Elsy). Il devra dorénavant appliquer son savoir-faire virtuel sur de vraies filles afin de les libérer d\'âmes damnées échappées des enfers et trouvant refuge dans le cœur de jeunes demoiselles. Problème ! Keima déteste les filles réelles. Voilà qui s\'annonce compliqué.', '7.67', 'https://cdn.myanimelist.net/images/userimages/19870.jpg?t=1649045400');
INSERT INTO `products` (`id`, `title`, `Synopsis`, `Score`, `Image`) VALUES
(72, 'Gamers!', 'Cette série nous entraîne dans le quotidien de jeunes lycéens jouant aux jeux vidéos dont :\r\nKeita Amano, un jeune homme solitaire et passionné de jeux vidéos, Karen Tendō la présidente du club de jeux vidéos, Chiaki Hoshinomori qui se dispute souvent avec Keita et Tasuku Uehara, qui se dit être heureux dans le monde réel, mais qui en réalité, adore les jeux vidéos.', '6.79', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(73, 'To LOVE-Ru', 'Rito Yuuki, jeune lycéen de 15 ans, vit en compagnie de sa sœur et de son père. C\'est un jeune homme très timide et il est amoureux de la belle Haruna Sairenji depuis l\'école primaire. Un jour, alors qu\'il est sous la douche à avoir des mauvaises pensées sur Haruna, son bain explose et apparait une jeune femme nue...\r\n\r\nC\'était la première rencontre entre Lala Deviluke et Rito Yuuki.\r\n\r\nOn apprend alors que la belle Lala est une princesse extraterrestre venant de la planète Deviluke et que des hommes en noir sont chargés de la ramener chez elle afin qu\'elle se marie.\r\n\r\nElle décide finalement de rester sur Terre afin même de se marier avec Rito. Le père de Lala impose une condition : que Rito réussisse à sauver Lala des nombreux prétendant cherchant à la posséder sinon, la Terre sera détruite.', '7.00', 'https://cdn.myanimelist.net/images/userimages/104175.jpg?t=1402888800'),
(74, 'Akagami no Shirayuki-hime', 'Shirayuki est une jeune fille avec un certain talent pour l’identification et l’utilisation des plantes médicinales. Mais elle a un autre attribut : ses cheveux ont la même couleur qu’une pomme rouge ! Cette couleur de cheveux très rare attire l’attention du prince Raji, qui gouverne le royaume de Tanbarun. Celui-ci a la ferme intention de faire de Shirayuki sa concubine ! Mais la jeune fille aux cheveux rouges ne veut pas se laisser faire : elle n’est pas un simple objet, mais un être humain ! Elle décide alors de s’enfuir dans la forêt, après avoir coupé sa chevelure. Elle fait alors la rencontre d’un vagabond nommé Zen et découvre peu à peu qu\'il est en réalité le second prince du royaume voisin.', '7.77', 'https://cdn.myanimelist.net/images/userimages/352759.jpg?t=1656282600'),
(75, 'Sukitte Ii na yo.', 'Tachibana Mei a passé ses 16 ans de vie sans avoir un petit ami ou sans se faire des amis. Un jour, elle blesse le garçon le plus populaire à l\'école, Yamato Kurosawa mais, pour une raison inconnue, celui-ci semble bien l\'aimer et prétend unilatéralement qu\'ils sont amis.\r\nEn plus de protéger Mei d\'un harceleur, il lui donne un baiser.', '7.43', 'https://cdn.myanimelist.net/images/userimages/93378.jpg?t=1608420600'),
(76, 'Shinmai Maou no Testament', 'L’histoire nous entraîne dans le quotidien ecchi de Toujo Basara, qui se retrouve à vivre avec 2 belles-sœurs, suite au remariage de son père.\r\nCependant, les sœurs Mio & Maria, sont en réalité de jeunes Démons. L’une est la Démon-Reine et l’autre une Succube.\r\nMais Basara fait partie du clan des Héros, qui est l’ennemi naturel des Démons. Et un incident conduit Basara au rang de Maître de Mio.\r\nMalheureusement, la vie de l’adolescent est loin d’être de tout repos puisque Mio est poursuivie par les autres tribus de Démons et les clans des Héros.', '6.73', 'https://cdn.myanimelist.net/images/userimages/3437971.jpg?t=1649273400'),
(77, 'School Days', 'Makoto est amoureux de Kotonoha. Il la voit chaque jour dans le train qui les mène à l’école, seulement, il n’a pas le courage de lui dire quoi que ce soit et se contente de la regarder de loin. Tout change lorsqu’il prend une photo d’elle avec son téléphone portable. Photo que Sekai, une de ses camarades de classe, voit avant de proposer au timide Makoto de lui arranger le coup avec la jeune fille. Le trio se retrouve donc à un déjeuner improvisé par l’entremetteuse, afin que les deux tourtereaux fassent plus ample connaissance. Mais si Sekai est elle aussi amoureuse de Makoto, pourquoi tient-elle tant à le voir avec Kotonoha ?', '5.55', 'https://cdn.myanimelist.net/images/userimages/9646.jpg?t=1656887400'),
(78, 'Kimi ni Todoke', 'Sawako Kuronuma souhaite faire le bien autour d\'elle, et pour cela doit commencer par parvenir à sympathiser avec ses camarades de classe. Chose difficile à faire, car ces derniers sont terrorisés par l\'apparence de la jeune fille, qui se retrouve ainsi assimilée à l\'image de Sadako (voir le film The Ring). Malgré tout, Sawako ne leur en veut pas, et elle cherche même à utiliser cette situation embarrassante pour se rapprocher d\'eux. Bien qu\'elle préfèrerait de loin devenir quelqu\'un d\'apprécié et de populaire tel que le beau Shôta Kazehaya. Selon elle, il est un jeune homme sociable et agréable, quelqu\'un de « rafraîchissant » et gentil à l\'égard de tout le monde, elle y comprise.\r\nCe qu\'elle ne sait pas encore, c\'est qu\'il est en vérité beaucoup plus sensible à la présence de Sawako qu\'à celle des autres filles de son entourage…', '8.00', 'https://cdn.myanimelist.net/images/userimages/93378.jpg?t=1608420600'),
(79, 'Rakudai Kishi no Cavalry', 'Certains magiciens sont capables de créer des armes en les matérialisant avec leur âme. Ils sont appelés Magic Knights. Notre héros, Ikki Kurogane est élève dans une académie ayant pour but de former les futurs Magic Knights. Cependant, il ne possède aucune compétence magique, ce qui lui vaut le surnom de Failed Knight. Un jour, Stella, une princesse venue d’une contrée étrangère qui est en plus la meilleure élève de l’académie le met au défi. Quel en est l’enjeu ? Le perdant de cet affrontement devra obéir au gagnant jusqu’à la fin de sa vie…', '7.46', 'https://cdn.myanimelist.net/images/userimages/1269655.jpg?t=1656982200'),
(80, 'Gekkan Shoujo Nozaki-kun', 'L’histoire nous entraîne dans la vie quotidienne de la lycéenne Chiyo Sakura, amoureuse de Nozaki, un élève studieux.\r\nUn jour, Sakura découvre que Nozaki est en réalité un célèbre mangaka spécialisé dans le shoujo, et devient son assistante.', '7.85', 'https://cdn.myanimelist.net/images/userimages/3667805.jpg?t=1584264000'),
(81, 'Saikin, Imouto no Yousu ga Chotto Okashiinda ga.', 'L’histoire nous entraîne dans la vie de la lycéenne Mitsuki Kanzaki qui vit avec son beau-frère, Yuya, depuis que sa mère s’est remariée.La jeune fille est de nature plutôt distante juqu’au jour où elle se retrouve coincée avec l’esprit d’une jeune fille, du nom de Hiyori Kotobuki.Maintenant, Mitsuki doit jouer les entremetteuses pour que Hiyori tombe amoureuse de Yuya afin qu’elle puisse retourner au Paradis.', '6.22', 'https://cdn.myanimelist.net/images/userimages/2261967.jpg?t=1656981000'),
(82, 'Papa no Iukoto wo Kikinasai!', 'Étudiant en première année d\'université, Segawa Yuta est un jeune homme qui a été élevé depuis presque toujours par sa soeur Yuri, en raison de la disparition de ses parents dans le passé. Cependant à présent, il vit seul, car elle s\'est mariée à un homme plus âgé qu\'elle, et qu\'elle n\'a donc plus vraiment le temps de s\'occuper de son frère.\r\nMais un jour, Yuri revient voir Yuta, pour lui demander un grand service : celui de prendre soin de ses trois filles Sora, Miu et Hina, pendant qu\'elle part en voyage avec son mari. Le concerné accepte d\'aider sa soeur, néanmoins contre son gré. Après tout, c\'est juste pour un voyage. Mais cela ne se passe malheureusement pas comme prévu, car l\'avion dans lequel voyageaient Yuri et son homme, a disparu... Ainsi, pour ne pas que les trois jeunes filles soient adoptées séparément, le jeune homme décide de les garder dans son appartement. Et c\'est de cette manière que la vie paisible de Yuta va être bouleversée à jamais...', '7.28', 'https://cdn.myanimelist.net/images/userimages/887295.jpg?t=1656963000'),
(83, 'Little Busters!: Refrain', 'Riki est un jeune orphelin qui a perdu ses parents lorsqu\'il était encore enfant. Mais un groupe composé de trois garçons et d\'une fille, les Little Busters va l\'aider. Le chef de ce groupe est Kyousuke Natsume qui a une petite sœur faisant également partie du groupe, Rin. Les autres membres sont Masato Inohara et Kengo Miyazawa.\r\nA force de jouer avec eux, Riki est accepté et reconnu en tant que membre du Little Busters, jusqu\'à en presque oublier la mort de ses parents.\r\nDésormais, les Little Busters sont en deuxième année de lycée, sauf le chef qui est en troisième année, et toujours ensemble, ils profitent de leur vie scolaire...', '8.20', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(84, 'Fate/stay night', 'Tiré d\'un eroge visual novel de Type‑Moon à l\'instar de Tsukihime, Fate/stay night nous conte l\'histoire de Shirô Emiya, un jeune homme capable d\'analyser la structure des objets grâce à la magie. Enfant, Shirô fut témoin du dénouement tragique d\'une guerre occulte opposant sept magiciens et leurs serviteurs et qui détruisit son quartier. Recueilli par un magicien, désormais décédé, Shirô est devenu un jeune homme solitaire doté de pouvoirs limités, capable de réparer les objets d\'instinct et de lancer quelques sorts. Au cours d\'une nuit tragique où il se retrouve à nouveau confronté à la guerre pour le saint Graal, Shirô invoque Saber, l\'ultime serviteur, et devra affronter les six autres magiciens malgré ses limites.', '7.29', 'https://cdn.myanimelist.net/images/userimages/199926.jpg?t=1636987800'),
(85, 'Prison School', 'Le lycée Hachimitsu est réputé pour être un des plus sévères du pays. Jusqu’à cette année, il était réservé aux filles, mais les garçons y sont désormais autorisés. Seulement, comme c’est l’année-test, ils ne sont que cinq dans tout l’établissement ! Kiyoshi est l’un d’eux. Il est particulièrement timide mais cherche à discuter avec des filles. Dès le premier jour, il fait connaissance avec Chiyo car la jeune fille est amatrice de sumo. Mais à peine ont-ils lié amitié que ses quatre camarades garçons décident d’aller espionner les filles aux bains ! Kiyoshi acceptera-il de les accompagner, au risque de perdre la confiance de son amie ?', '7.62', 'https://cdn.myanimelist.net/images/userimages/2513325.jpg?t=1656945000'),
(86, 'Date A Live', 'Itsuka Shido est un jeune lycéen vivant une vie paisible jusqu\'à ce qu\'une explosion détruise la ville et qu\'une jeune fille en armure apparaisse devant lui.\r\n\r\nQuelques instants après, sa sœur adoptive Kotori, qui est en réalité commandante de l\'organisation militaire Ratatoskr, lui apprend que la fille en question est un esprit qui déstabilise l\'espace-temps.\r\n\r\nLe seul moyen d\'arrêter cette menace est que Shido utilise son mystérieux pouvoir lui permettant de sceller les pouvoirs d\'un esprit dans son corps. Cependant, cette méthode ne fonctionne que si l\'esprit l\'affectionne et a confiance en lui.\r\n\r\nAinsi, l\'organisation Ratatoskr va lui proposer sortir avec cet esprit pour gagner sa confiance et son affection.', '7.17', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(87, 'Golden Time', 'L’histoire nous entraîne dans la vie quotidienne de Tada Banri, qui intègre l’université privée de Droit à Tokyo. A la rentrée, les étudiants de première année, Tada & Yanagisawa Mitsuo, sont légèrement perdus. C’est ainsi qu’ils rencontrent une ravissante demoiselle tenant un bouquet de rose et qui félicite Mitsuo pour son entrée à la faculté. Tada Banri tombe immédiatement sous le charme de cette mystérieuse demoiselle. Mais il découvre que Kaga Kouko (la jeune fille), est l’amie d’enfance de Mitsuo. Ils s’étaient même promis de se marier ensemble, une fois adulte. Pour tenir sa promesse, Kouko a passé secrètement l’examen d’entrée pour l’université de Droit…', '7.75', 'https://cdn.myanimelist.net/images/userimages/3836941.jpg?t=1572711600'),
(88, 'ReLIFE', 'L’histoire nous entraîne au côté de Arata Kaizaki, un homme sans emploi de 27 ans, qui fait la rencontre de Ryo Yoake, membre de l’institut ReLife Research.\r\nCe dernier lui propose d’être le cobaye d’un nouveau médicament qui permet de rajeunir jusqu’à ses 17 ans.\r\nAvec sa nouvelle apparence, Arata doit retourner au lycée durant une année et revivre les péripéties que réservent la vie d’adolescent.', '7.99', 'https://cdn.myanimelist.net/images/userimages/5159879.jpg?t=1656969000'),
(89, 'Mahouka Koukou no Rettousei', 'La \"Magie\" que nous connaissons n\'est issue ni des légendes, ni des contes de fées. Elle est devenue une réelle technologie depuis près d\'un siècle. Plusieurs pays de ce monde s\'opposent dans une course à la formation de \"Magiciens\". Tatsuya Shiba est un étudiant sans capacités magiques inscrit au Premier Lycée de Magie ;il y étudie avec sa sœur Miyuki, qui se trouve être la meilleure élève parmi les première années.', '7.43', 'https://cdn.myanimelist.net/images/userimages/89975.jpg?t=1656255000'),
(90, 'Sakura-sou no Pet na Kanojo', 'Kanda Sorata est un lycéen qui vit au Sakurasō, un dortoir pour les élèves à problèmes du lycée de Sorata. Un jour, Shiina Mashiro, une superbe jeune fille et brillante artiste, arrive au Sakurasō.\r\n\r\nSorata se dit qu\'il doit protéger Mashiro des locataires farfelus de Sakurasō, mais Mashiro a un secret surprenant : elle n\'a aucune idée de comment prendre soin d\'elle-même. Elle se perd si elle sort et sa chambre est un désordre complet. Les camarades de dortoir de Sorata le désignent alors comme le maître de Mashiro, et c\'est ainsi qu\'un garçon ordinaire et une fille brillante vont devoir vivre comme un maître et son animal de compagnie.', '8.11', 'https://cdn.myanimelist.net/images/userimages/2981555.jpg?t=1656849600'),
(91, 'Chuunibyou demo Koi ga Shitai!', 'Togashi Yuta est un garçon qui plus jeune a souffert de chuunibyou, c\'est-à dire qu\'il s\'inventait une vie fictive et s\'éloignait des autres, se croyant supérieur à eux et pensant être doté de pouvoirs surnaturels. Mais aujourd\'hui, Yûta a honte de son passé et essaye de repartir à zéro au lycée. En effet, il a choisit un lycée où personne ne le connait et commence dès la rentrée à se faire des amis. Cependant, il rencontre Takanashi Rikka, une élève de sa classe qui souffre encore beaucoup de chuunibyou. Celle-ci découvre son passé et va essayer de l\'entraîner dans son monde imaginaire.', '7.72', 'https://cdn.myanimelist.net/images/userimages/39613.jpg?t=1656839400'),
(92, 'Clannad', 'Clannad TV présente la vie d\'un jeune lycéen, Tomoya Okazaki , qui s\'avère être un recalé, également vu par les autres comme un délinquant. Plutôt lassé de sa vie, ses journées s\'avèrent être trop monotones, rien qui ne relève le défi de l\'intéresser. Il espère donc voir sa vie changer un jour, et fait ainsi la rencontre de Nagisa Furukawa, étudiante dans le même lycée que lui, et qui semble plus mystérieuse qu\'elle ne paraît. Ce dernier commence à faire des rêves étranges, peut-être liés à cette rencontre, et ne cesse de rencontrer une à une des filles ayant chacune des personnalités particulières. C\'est ainsi que la vie de Tomoya sera bouleversée comme il ne l\'aurait jamais imaginé !', '8.01', 'https://cdn.myanimelist.net/images/userimages/309079.jpg?t=1648486800'),
(93, 'Yahari Ore no Seishun Love Comedy wa Machigatteiru.', 'Le jeune Hachiman a une vision des plus pessimistes de la vie. De toute façon, sa situation actuelle ne le pousse guère à déborder d\'optimisme : pas d\'amis, pas de petite amie et sa capacité à envisager l\'avenir est, selon ses propres dires, complètement HS. Pour le faire changer, son professeur le pousse à rejoindre un club scolaire qui s\'avère être dirigé par la plus belle fille du lycée, Yukino, surnommée « la beauté de glace ». Perfectionniste au possible, cette dernière considère que la destinée des personnes d\'exception est de guider les moins chanceux. Hachiman fera-t-il partie des brebis galeuses remises sur le droit chemin par Yukino ou bien cette comédie sentimentale adolescente tombera-t\'elle à plat comme le jeune homme s\'y attend ?', '8.02', 'https://cdn.myanimelist.net/images/userimages/3728321.jpg?t=1466272800'),
(94, 'Bakemonogatari', 'Bakemonogatari, c\'est l\'histoire de Koyomi Araragi, un étudiant de troisième année qui est presque un être humain dans le sens où il fut un vampire par le passé ! L\'histoire commence le jour où il voit tomber des escaliers l\'une de ses camarades de classe, Hitagi Senjôgahara. Il la sauve d\'une chute périlleuse, mais, à la plus grande surprise de Koyomi, celle-ci ne pèse rien (ou presque) ! Après quoi, cette dernière, d\'habitude silencieuse, le menace et lui intime de garder le silence. Ce dernier refuse de rester indifférent et lui propose de l\'aider à résoudre son problème.', '8.34', 'https://cdn.myanimelist.net/images/userimages/321412.jpg?t=1421065800'),
(95, 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka', 'L’histoire nous entraîne dans les mésaventures d’un groupe de guerriers.\r\nLa ville labyrinthe, Orario, aussi appelé Dungeon est le lieu où se dirige tous les guerriers qui veulent vivre dangereusement.\r\nBell Clanel est un jeune garçon qui veut devenir plus fort après avoir été sauvé par Eyes Warenstein, une belle et implacable épéiste, qui ne le laisse pas indifférent.\r\nA ses côtés, Clanel peut compter sur Hestia, une divinité immature, qui est tombée amoureux de lui et qui s’aident mutuellement dans leurs quêtes.', '7.56', 'https://cdn.myanimelist.net/images/userimages/3966203.jpg?t=1655901000'),
(96, 'Elfen Lied', 'Lucy, une mutante aux pouvoirs dangereux (diclonius) s\'échappe du laboratoire où elle était retenue pour des expériences. Elle tue toux ceux qui se dressent sur son passage. À peine sortie du laboratoire, un sniper lui tire dessus et elle tombe à la mer.\r\nLe lendemain, Kota, revenu dans sa ville natale, donne rendez-vous à sa cousine Yuka. En allant se promener sur la plage, ils découvrent une jeune fille nue, ayant perdue la mémoire. Ils la recueillent et la surnomment Nyu, car c\'est le seul mot qu\'elle peut prononcer. Mais Nyu n\'est autre que Lucy.', '7.50', 'https://cdn.myanimelist.net/images/userimages/11081.jpg?t=1656976800'),
(97, 'Hataraku Maou-sama!', 'Le roi démon vient d\'être vaincu par le héros lors d\'une guerre sanglante opposant les démons aux humains. Dû à sa défaite, le roi démon s\'enfuit avec son meilleur commandant en ouvrant une porte vers le monde des humains.\r\n\r\nEn arrivant a Tokyo, la langue des humains leur est étrangère. C\'est dans cet univers que notre roi démon rebaptisé Sadao Maou et son commandant Shirou Ashiya doit survivre et s\'habituer à vivre comme des humains.', '7.78', 'https://cdn.myanimelist.net/images/userimages/2389903.jpg?t=1656271800'),
(98, 'Darling in the FranXX', 'Dans un lointain futur, le Terre est en ruines et l’humanité s’est retranchée dans une ville fortifiée mobile, Plantation. Un quartier est dédié à la formation de jeunes pilotes qui ne connaissent rien du monde extérieur. Leur seul but dans la vie est d’apprendre à piloter des robots, les Franxx, afin d’affronter un mystérieux ennemi géant mais invisible. Parmi eux, Hiro (Code 016) était un enfant particulièrement doué, promis à devenir un grand pilote, mais qui a eu le malheur d’échouer ! Mis au rebut, son inaptitude à piloter le condamne à l’oubli. Un jour débarque une jeune fille appelée Zero Two dont le visage est orné de deux cornes. Elle le désigne d’office comme son nouvel équipier…', '7.23', 'https://cdn.myanimelist.net/images/userimages/483536.jpg?t=1648797600'),
(99, 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai', 'Il existe une rumeur, cette dernière concerne un phénomène mystérieux appelé \"syndrome de la puberté\".\r\n\r\nSakuta Azusagawa est un jeune lycéen qui fait la rencontre soudaine d\'une jeune femme. La personne en question est Mai Sakurajima, une senpai du même établissement que lui. Cette dernière est aussi une actrice célèbre qui s\'est retirée de l\'industrie du cinéma.\r\n\r\nPour une raison étrange, les gens autour de Mai ne peuvent plus la voir. Sakuta, intrigué, entreprend de résoudre ce mystère.\r\n\r\nAu fur est à mesure qu\'il passe du temps avec Mai, d\'étranges sentiments commencent à naître en lui.', '8.27', 'https://cdn.myanimelist.net/images/userimages/4150781.jpg?t=1656977400'),
(100, 'Shigatsu wa Kimi no Uso', 'Arima Kosei est un véritable prodige du piano ; enfant, il dominait tous ses rivaux en compétition et s\'était déjà fait un nom dans le domaine musical. Mais après la mort de sa mère, il a subit une forte dépression qui l\'a forcé à être dégoûté de son propre instrument. Deux ans après le drame, continuant de considérer sa vie comme insipide, Arima se contente de vivre sa vie sans réel but… jusqu\'à ce qu\'il rencontre Miyazono Kaori, une jeune violoncelliste qui, elle aussi, semble exceller dans son art…', '8.66', 'https://cdn.myanimelist.net/images/userimages/236056.jpg?t=1650286200'),
(101, 'Sword Art Online', 'En 2022, l\'humanité a réussi à créer une réalité virtuelle. Grâce à un casque, les humains peuvent se plonger entièrement dans le monde virtuel en étant comme déconnectés de la réalité, et Sword Art Online est le premier MMORPG a utiliser ce système. Mais voila que le premier jour de jeu, 10 000 personnes se retrouvent piégées dans cette réalité virtuelle par son créateur : Akihiko Kayaba. Le seul moyen d\'en sortir est de finir le jeu. Mais ce ne sera pas facile de sortir de ce monde virtuel puisque si un joueur perd la partie, il meurt également dans la vraie vie.\r\n\r\nKirito décide alors de partir à la conquête du jeu en solo, avec pour avantage le fait de faire partie des 1 000 ex-bêta-testeurs, mais arrivera-t-il à terminer les 99 donjons et leurs boss ?', '8.31', 'https://cdn.myanimelist.net/images/userimages/3441293.jpg?t=1656820800'),
(102, 'Owari no Seraph', 'Un jour, un mystérieux virus décime chaque humain de plus de 13 ans. Au même moment, les Vampires ont émergés et asservis les enfants, seuls survivants de l’épidémie.\r\nL’histoire nous entraîne au côté de Yuuichirou Hyakuya, un esclave chargé de donner son sang à des aristocrates.\r\nAyant perdu son frère lors de son évasion, Yuuichirou se promet de tuer tous les Vampires, et pour cela, il rejoint la résistance pour délivrer les esclaves.', '8.31', 'https://image.adkami.com/1411.jpg?=1443274369');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Index pour la table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Index pour la table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Index pour la table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT pour la table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=224;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
